export const articleDetailResponse = {
  article: {
    id: 183,
    name: 'Coca Cola 2',
    barcodes: [],
    tags: [
      { id: 4, tag: 'Sweets', created: '2019-10-18 08:32:56' },
      { id: 49, tag: 'drinks', created: '2019-10-19 20:11:05' },
      { id: 50, tag: 'test', created: '2019-10-20 00:01:43' },
    ],
    amount: 501,
    isActive: true,
    isActivatable: false,
    usageCount: 147,
    precursor: {
      id: 145,
      name: 'Coca Cola',
      barcodes: [],
      tags: [],
      amount: 501,
      isActive: false,
      isActivatable: false,
      usageCount: 147,
      precursor: {
        id: 143,
        name: 'Coca Cola',
        barcodes: [],
        tags: [],
        amount: 501,
        isActive: false,
        isActivatable: false,
        usageCount: 146,
        precursor: {
          id: 141,
          name: 'Coca Cola',
          barcodes: [],
          tags: [],
          amount: 501,
          isActive: false,
          isActivatable: false,
          usageCount: 144,
          precursor: {
            id: 116,
            name: 'Coca Cola',
            barcodes: [],
            tags: [],
            amount: 1000,
            isActive: false,
            isActivatable: false,
            usageCount: 140,
            precursor: {
              id: 34,
              name: 'Coca Cola',
              barcodes: [],
              tags: [],
              amount: 1000,
              isActive: false,
              isActivatable: false,
              usageCount: 126,
              precursor: {
                id: 33,
                name: 'Coca Cola',
                barcodes: [],
                tags: [],
                amount: 1000,
                isActive: false,
                isActivatable: true,
                usageCount: 6,
                precursor: null,
                created: '2019-01-27 19:39:21',
              },
              created: '2019-01-28 09:12:56',
            },
            created: '2019-06-18 22:45:26',
          },
          created: '2019-10-07 19:21:11',
        },
        created: '2019-10-12 19:23:27',
      },
      created: '2019-10-14 21:17:18',
    },
    created: '2019-10-19 18:06:12',
  },
};
